packages:
    - "packages/*"

catalog:
    "@effect/platform-node": 4.0.0-beta.70
    "@opentelemetry/api": ^1.9.1
    "@opentelemetry/exporter-trace-otlp-http": ^0.222.0
    "@opentelemetry/sdk-trace-node": ^2.11.0
    "@types/bun": 1.3.14
    "@types/node": ^22.19.19
    "@typescript/native-preview": 7.0.0-dev.20260421.2
    alchemy: 2.0.0-beta.43
    drizzle-kit: 1.0.0-rc.3
    drizzle-orm: 1.0.0-rc.3
    effect: 4.0.0-beta.70
    miniflare: 4.20260529.0
    playwright: 1.60.0
    tsx: 4.22.4
    typescript: ^5.9.3
    vite: npm:@voidzero-dev/vite-plus-core@^0.1.24
    vite-plus: ^0.1.24
    vitest: npm:@voidzero-dev/vite-plus-test@^0.1.24
    wrangler: ^4.96.0

catalogMode: prefer
overrides:
    vite: "catalog:"
    vitest: "catalog:"
peerDependencyRules:
    allowAny:
        - vite
        - vitest
    allowedVersions:
        vite: "*"
        vitest: "*"
