packages:
    - "packages/*"

catalog:
    "@effect/platform-node": 4.0.0-beta.70
    "@types/node": ^22.19.19
    "@typescript/native-preview": 7.0.0-dev.20260421.2
    alchemy: 2.0.0-beta.43
    drizzle-kit: 1.0.0-rc.3
    drizzle-orm: 1.0.0-rc.3
    effect: 4.0.0-beta.70
    typescript: ^5.9.3
    vite: npm:@voidzero-dev/vite-plus-core@latest
    vite-plus: ^0.1.24
    vitest: npm:@voidzero-dev/vite-plus-test@latest
    wrangler: ^4.96.0

catalogMode: prefer
overrides:
    vite: "catalog:"
    vitest: "catalog:"
peerDependencyRules:
    allowAny:
        - vite
        - vitest
    allowedVersions:
        vite: "*"
        vitest: "*"
